#端口号
server:
  port: 8081
  servlet:
    context-path: /
#服务名
spring:
  application:
    name: hotel
#返回json的全局时间格式
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8

  #环境设置 ：dev开发环境    test测试环境   prod生产环境
  profiles:
    active: dev
  #配置阿里巴巴数据源的四大件
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/k9508hotel?useSSL=false&characterEncoding=utf8
    username: root
    password:
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL


#配置mybatis
mybatis-plus:
  type-aliases-package: com.hyl.model
  configuration:
    #日志的配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml
#逻辑删除 1删除，0未删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

